source $HOME/.config/nvim/general/leader.vim
source $HOME/.config/nvim/general/coc.vim
source $HOME/.config/nvim/plugin/plugs.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/general/functions.vim
source $HOME/.config/nvim/general/airline.vim
source $HOME/.config/nvim/general/themes.vim
source $HOME/.config/nvim/general/fzf.vim
source $HOME/.config/nvim/general/startify.vim
source $HOME/.config/nvim/general/farr.vim
source $HOME/.config/nvim/general/git_things.vim