# Follwing the example in the ci URL

version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  print_pipeline_id:
    description: "Testing the work with commands property"
    parameters:
      to:
        type: string
        default: "$CIRCLE_WORKFLOW_ID"
    steps:
      - run: echo << parameters.to >>

jobs:
  Test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:

workflows:
  Build:
    jobs:
    - Test
